### ISSUE TITLE
2.2.x Mod changes

### ISSUE THREAD

**Issue by Kenja-mc** [Kenja-mc/shattered_stars#24]
## Additions
- [x] Yungs Better Nether Fotresses
- [x] In Control
- [x] Target Dummy

## Removals
- [x] Infectum
- [x] First Aid

**Comment by Strange-Bird-of-the-Moon** [comment]
Add mmmmmmm (training dummy) if it is not already

**Comment by Kenja-mc** [comment]
For some reason packwiz or prism launcher is not properly importing In Control

**Comment by Kenja-mc** [comment]
Looks like the issue is that its not part of the client version for some reason.
![](https://i.imgur.com/qF6haem.png)

**Comment by Kenja-mc** [comment]
Updated incontro.pw.toml and fx-contro.pw.toml to make them both client and server side.

![](https://i.imgur.com/CwzjhtT.png)
