### ISSUE TITLE
Apotheosis Affix Issues

### ISSUE THREAD

**Issue by Strange-Bird-of-the-Moon** [Kenja-mc/shattered_stars#25]
- The ease of getting powerful equipment off of random mobs and bosses (especially in the nether) disincentives mining and crafting.
  - Reduced drop rates help, but don't change the fact that crafted equipment is just always going to be worse
- Affixes work well with Tetra swords and tools, but there's no way to get combat effects on weapons like spears, which need to be modified from shovels.
- Affixes are removed if you make Tetra modifications to bows.
  - Not sure why this is only seems to happen with bows.  
- Some affixes are just broken, such as the one that gives instant health upon taking damage
- It kind of sucks getting large amounts of leather and chainmail equipment with a good affixes
- This is perhaps more of a matter of opinion, but one of the central features of Tetra is the idea that rather than constantly crafting new equipment, you repair and upgrade what you already have.  Affixes strongly discourage this, since you will likely get progressively better drops as you move to harder areas (i.e. I may have spent time tinkering with and upgrading a pick with a good affix; but that all goes out the window once I find one that's better).

**Comment by Strange-Bird-of-the-Moon** [comment]
I think most of this could be solved by changing the drops to a nametag-like item that can be applied to equipment of the user's choice.  We would want any new affixes to clear any previous affixes, so you can't just stack every modifier on one weapon (at least until late game).

**Comment by Kenja-mc** [comment]
We will disable affixes for now while you work to balance Tetra. In the future we may implement affix creation through some magic mod.

**Comment by Kenja-mc** [comment]
Ive changed it to remove affixes and gems from all loot and mob drops.
Bosses are the only way to get gems now.

**Comment by Kenja-mc** [comment]
Will revisit in future
