### ISSUE TITLE
Thermal Cultivation Crops

### ISSUE THREAD

**Issue by Strange-Bird-of-the-Moon** [Kenja-mc/shattered_stars#3]
- [x] Add nutrition values and tags for recipes (e.g. barley should be tagged as a grain).
- [x] Remove duplicate entries with Farmer's Delight.
-  ~~[ ] Add improvements from Farmer's Delight (e.g. beans should be able to grow with a rope trellis).~~
- ~~[ ] Make compatible with Farmer's Delight existing cooking recipes, and add new ones.~~
-  ~~[ ] Add coffee and tea.  They exist as crops but don't currently seem to have a use.  Maybe add caffeine as a nutrient?~~

**Comment by Kenja-mc** [comment]
Entry 2 is being worked on in #19

**Comment by Kenja-mc** [comment]
Entry 1 is being worked on in #23

**Comment by Kenja-mc** [comment]
The last 3 will be split off into separate tickets.

- #27 
- #28
- #29
