### ISSUE TITLE
Right-Click to Harvest/Replant is broken for 2-high crops

### ISSUE THREAD

**Issue by Strange-Bird-of-the-Moon** [Kenja-mc/shattered_stars#5]
- Right-Clicking on a crop should harvest and replant it.  If done with a knife, it should also yield straw for certain crops.
- This is broken with 2 block high crops from Thermal Cultivation, like Flax and Amaranth.  Targeting the bottom block will replant, but will leave the top part floating.  Targeting the top part will harvest both blocks, but will not replant.
- Industrial hemp (Immersive Engineering) must be left-clicked and cannot be automatically replanted.

**Comment by Kenja-mc** [comment]
Splitting up this issue into sub-issues.

> Right-Clicking on a crop should harvest and replant it. If done with a knife, it should also yield straw for certain crops.

See issue #21 

> This is broken with 2 block high crops from Thermal Cultivation, like Flax and Amaranth
> Industrial hemp (Immersive Engineering) must be left-clicked and cannot be automatically replanted.

I will add Amaranth and Industrial Hemp to Quark's simple harvest whitelist.

I will be removing Thermal Cultivation Flax because it is functionally similar to Hemp. See issue #19.

**Comment by Kenja-mc** [comment]
I updated Hemp so you can right click to harvest, but you need to harvest from the bottom.

Amaranth and Corn are more problematic. I tried setting it in the quark config with these commands:
```
"thermal:amaranth[age=6,top=false],thermal:amaranth[age=0,top=false]",
"thermal:corn[age=6,top=false],thermal:corn[age=0,top=false]"
```

However, I get an issue with floating crops.
![image](https://i.imgur.com/ErHTBGZ.png)

This is likely a COFH problem.
I am ignoring those crops for now.

**Comment by Kenja-mc** [comment]
Potentially useful script by ChiefArug#4639 on the latvian.dev discord

```js
let Block = java('net.minecraft.world.level.block.Block')
onEvent('block.right_click', event => {
    let block = event.block
    if (block.hasTag('minecraft:crops')) {
        let mcLevel = event.level.minecraftLevel
        let blockState = mcLevel.getBlockState(block.pos)
        let mcBlock = blockState.block
        let mcPlayer = event.player.minecraftPlayer
        if (mcBlock.isMaxAge(blockState)) {
            let loot = Block.getDrops(blockState, mcLevel, block.pos, null, mcPlayer, mcPlayer.getMainHandItem())
            let seedYeeted = false
            for (let i in loot) {
                if (loot[i].asKJS().id == mcBlock.getCloneItemStack(mcLevel, block.pos, blockState).asKJS().id) {
                    loot[i].count--
                    seedYeeted = true
                    break
                }
            }
            loot.forEach(item => {
                Block.popResource(mcLevel, block.pos, item)
            })
            if (seedYeeted) {
                block.set(block.id, {age: '0'})
                event.server.runCommandSilent(`playsound minecraft:block.crop.break block @a ${block.x} ${block.y} ${block.z}`)
            } else { //if no seed was dropped for some odd reason
                mcLevel.destroyBlock(block.pos, true, null, 32)
            }
            event.cancel()
            event.player.swingArm(event.hand)
        }
    }
})
```
